name: Update Pac-Man Graph

on:
  schedule:
    - cron: "0 0 * * *"  # Executa diariamente à meia-noite
  workflow_dispatch:      # Permite executar manualmente
  push:
    branches: [ "main" ]

jobs:
  generate-graph:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Generate Pac-Man Graph
        uses: jstrieb/github-activity-readme@master
        with:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: guumarques  # Substitua pelo seu username
